name: "stadtanalyse"
version: "1.0.0"
config-version: 2
profile: "stadtanalyse"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  city_lat: 52.52
  city_lon: 13.405
  on_time_threshold_seconds: 120
  severe_delay_threshold_seconds: 600

models:
  stadtanalyse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: gold
      +materialized: table
      dims:
        +materialized: table

seeds:
  stadtanalyse:
    +schema: silver
    +quote_columns: false

data_tests:
  stadtanalyse:
    +severity: warn
